### ISSUE TITLE
Combining same domains with different subdomains

### ISSUE THREAD

**Issue by TheUntouchable** [qyqsoft/Bitwarden-Vault-Cleaner#1]
Hey und danke erstmal für das super Tool! 

Nach den Kommentaren im Code gehe ich davon aus dass ich auf Deutsch schreiben kann ;)

Ich habe vor kurzem vom Firefox nach Bitwarden migriert und bin gerade dabei meine 300 Einträge zu bereinigen. Dabei sind mir viele doppelte Einträge wie zb account.bethesda.net und bethesda.net aufgefallen, die das gleiche Passwort haben.

Wäre es möglich, diese auf den Hauptteil der Domäne (bethesda.net) zusammenzufassen? VIelleicht wäre hierbei auch ein Abfragefenster von Vorteil bei dem zb unterschiedliche Benutzernamen angezeigt werden und welchen man behalten will.. Kp :D

Danke im Voraus!

Grüße

English:

Hey and thanks first of all for the super tool! 

After the comments in the code I assume that I can write in German ;)

I have recently migrated from Firefox to Bitwarden and am currently cleaning up my 300 entries. I noticed a lot of duplicate entries like account.bethesda.net and bethesda.net which have the same password.

Would it be possible to merge them to the main part of the domain (bethesda.net)? Maybe a query window would also be advantageous here where e.g. different usernames are displayed and which one you want to keep.... Kp :D

Thanks in advance!

Greetings

**Comment by qyqsoft** [comment]
Ich habe inzwischen eine Version 2 released wo es keinen Combine Knopf mehr gibt und dir vorher anzeigt wird welche Änderungen gemacht werden. Da kannst du prüfen ob alles passt. Die URLs werden jetzt gleich mit zusammengefügt, so lange du die vorgegeben Auswahl der Spalten beibehältst.

**Comment by TheUntouchable** [comment]
Sehr cool, probier ich gleich aus! Danke :)
